### ISSUE TITLE
Is this stable?

### ISSUE THREAD

**Issue by dcondrey** [ralcr/Jirassic#1]
I am thrilled to find this but attempts to build it resulted in numerous errors. Is this buildable?  Thx

**Comment by dcondrey** [comment]
I'd be happy to help you with this project if you want.  My knowledge of desktop development is limited but I can help you build a website to show it off and sell it.

**Comment by ralcr** [comment]
Hi, i was in the middle of re-architecting it and i committed a non working version, but it will be up and working this days.

**Comment by dcondrey** [comment]
thanks!
