### ISSUE TITLE
PopoverViewController exception

### ISSUE THREAD

**Issue by dcondrey** [ralcr/Jirassic#2]
PopoverViewController.swift:22: nil
2015-06-19 01:33:11.941 Jirassic[3968:65759] An uncaught exception was raised
2015-06-19 01:33:11.941 Jirassic[3968:65759] The class Jirassic.User must be registered with registerSubclass before using Parse.
2015-06-19 01:33:11.941 Jirassic[3968:65759] (
	0   CoreFoundation                      0x00007fff9550e03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9057276e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9550deed +[NSException raise:format:] + 205
	3   ParseOSX                            0x00000001001dc13e -[PFObject(Private) init] + 187
	4   Jirassic                            0x000000010003ba11 _TFC8Jirassic4UsercfMS0_FT_S0_ + 49
	5   Jirassic                            0x000000010003ba4c _TFC8Jirassic4UserCfMS0_FT_S0_ + 44
	6   Jirassic                            0x000000010003fe51 _TFC8Jirassic19LoginViewController11viewDidLoadfS0_FT_T_ + 97
	7   Jirassic                            0x0000000100040282 _TToFC8Jirassic19LoginViewController11viewDidLoadfS0_FT_T_ + 34
	8   CoreFoundation                      0x00007fff9541abdf -[NSSet makeObjectsPerformSelector:] + 223
	9   AppKit                              0x00007fff931ac11b -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1166
	10  AppKit                              0x00007fff93386a0e -[NSNib _instantiateNibWithExternalNameTable:options:] + 677
	11  AppKit                              0x00007fff9338665e -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 143
	12  AppKit                              0x00007fff93385957 -[NSViewController loadView] + 272
	13  AppKit                              0x00007fff93304f03 -[NSViewController _loadViewIfRequired] + 75
	14  AppKit                              0x00007fff93304e6d -[NSViewController view] + 30
	15  Jirassic                            0x000000010004f63a _TFC8Jirassic21PopoverViewController21createLoginControllerfS0_FT_CS_19LoginViewController + 362
	16  Jirassic                            0x000000010004e22e _TFC8Jirassic21PopoverViewController11viewDidLoadfS0_FT_T_ + 686
	17  Jirassic                            0x000000010004e382 _TToFC8Jirassic21PopoverViewController11viewDidLoadfS0_FT_T_ + 34
	18  CoreFoundation                      0x00007fff9541abdf -[NSSet makeObjectsPerformSelector:] + 223
	19  AppKit                              0x00007fff931ac11b -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1166
	20  AppKit                              0x00007fff9318b205 loadNib + 384
	21  AppKit                              0x00007fff9318a72b +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 313
	22  AppKit                              0x00007fff9318a4e7 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	23  AppKit                              0x00007fff9318a2b3 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
	24  AppKit                              0x00007fff93182e89 NSApplicationMain + 605
	25  Jirassic                            0x0000000100045d6d main + 109
	26  libdyld.dylib                       0x00007fff9d0d85c9 start + 1
	27  ???                                 0x0000000000000003 0x0 + 3
)
2015-06-19 01:33:11.986 Jirassic[3968:65759] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The class Jirassic.User must be registered with registerSubclass before using Parse.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9550e03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9057276e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9550deed +[NSException raise:format:] + 205
	3   ParseOSX                            0x00000001001dc13e -[PFObject(Private) init] + 187
	4   Jirassic                            0x000000010003ba11 _TFC8Jirassic4UsercfMS0_FT_S0_ + 49
	5   Jirassic                            0x000000010003ba4c _TFC8Jirassic4UserCfMS0_FT_S0_ + 44
	6   Jirassic                            0x000000010003fe51 _TFC8Jirassic19LoginViewController11viewDidLoadfS0_FT_T_ + 97
	7   Jirassic                            0x0000000100040282 _TToFC8Jirassic19LoginViewController11viewDidLoadfS0_FT_T_ + 34
	8   CoreFoundation                      0x00007fff9541abdf -[NSSet makeObjectsPerformSelector:] + 223
	9   AppKit                              0x00007fff931ac11b -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1166
	10  AppKit                              0x00007fff93386a0e -[NSNib _instantiateNibWithExternalNameTable:options:] + 677
	11  AppKit                              0x00007fff9338665e -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 143
	12  AppKit                              0x00007fff93385957 -[NSViewController loadView] + 272
	13  AppKit                              0x00007fff93304f03 -[NSViewController _loadViewIfRequired] + 75
	14  AppKit                              0x00007fff93304e6d -[NSViewController view] + 30
	15  Jirassic                            0x000000010004f63a _TFC8Jirassic21PopoverViewController21createLoginControllerfS0_FT_CS_19LoginViewController + 362
	16  Jirassic                            0x000000010004e22e _TFC8Jirassic21PopoverViewController11viewDidLoadfS0_FT_T_ + 686
	17  Jirassic                            0x000000010004e382 _TToFC8Jirassic21PopoverViewController11viewDidLoadfS0_FT_T_ + 34
	18  CoreFoundation                      0x00007fff9541abdf -[NSSet makeObjectsPerformSelector:] + 223
	19  AppKit                              0x00007fff931ac11b -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1166
	20  AppKit                              0x00007fff9318b205 loadNib + 384
	21  AppKit                              0x00007fff9318a72b +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 313
	22  AppKit                              0x00007fff9318a4e7 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	23  AppKit                              0x00007fff9318a2b3 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
	24  AppKit                              0x00007fff93182e89 NSApplicationMain + 605
	25  Jirassic                            0x0000000100045d6d main + 109
	26  libdyld.dylib                       0x00007fff9d0d85c9 start + 1
	27  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by ralcr** [comment]
Fixed, parse is no longer used.
