### ISSUE TITLE
Built but see no item in desktop bar top-right?

### ISSUE THREAD

**Issue by jc-alexo** [ralcr/Jirassic#31]
Hi. I have built this app in Xcode but it does not seem to put an icon in my tray and on running the app it simply opens a terminal instance, runs a process and then logs out. What is going wrong here?

**Comment by ralcr** [comment]
Hi, there are multiple targets, the status bar app is 'Jirassic' with the red icon, 'jirassic' is the command line app. You need to manage the schemes if is not already there.

**Comment by jc-alexo** [comment]
I manged to edit the schema to do the Jirassic.app like you said. For others trying to use this app, you have to remember to disable EVERYTHING to do with the Jirassic schema that has the terminal-like icon. ONLY have the Jirassic logo app with Run, Test, Profile etc.. ticked. Going to test that it works now. Thanks for getting back to me @ralcr !

**Comment by ralcr** [comment]
I renamed the CLI app schema to  jirassic-cmd to be more clear. Also made some other fixes that you might want to pull.
