### ISSUE TITLE
How to install without building?

### ISSUE THREAD

**Issue by sepehr** [ralcr/Jirassic#37]
No releases on github, no brew casks, and the website's appstore link is not working. I wonder, how can I install Jirassic without the need to build it?

**Comment by ralcr** [comment]
Hi, i haven't made any release yet because something important was always missing, but I'm close to finish it this month. I'll let you know.

**Comment by sepehr** [comment]
Looking forward to it; thanks.

**Comment by ralcr** [comment]
Hi, as of today the app is in the store, worths starting with the website http://www.jirassic.com
Thanks for the patience.

**Comment by sepehr** [comment]
That's great! thanks. 

That'd be also great if you consider a brew cask formula.

**Comment by ralcr** [comment]
Hi, the app itself will be only in the store, but is a good idea for the cli tools. I actually tried but failed, i'll open an issue and do it sometime or maybe someone else will do it.
