### ISSUE TITLE
Building app for personal use and contribution

### ISSUE THREAD

**Issue by neewy** [ralcr/Jirassic#51]
Hi! I would like to contribute to the project, but it seems that I can't build it — there is an error "Account does not have permissions to modify containers". How can I fix that in XCode 8.3?

**Comment by ralcr** [comment]
Hi, I guess is because of iCloud, you will naturally not be able to use my iCloud so you need to create your own container. Need to investigate how is possible to make this change and still pull commits without conflicts and pain. Would be cool if you can look into this if you want to contribute. (I'll make it more clear soon what i do with the contributions). Thanks and let me know if this is the issue.

**Comment by setegonz** [comment]
Any idea in how to start working on this?

**Comment by ralcr** [comment]
I think if we can have the app identifier outside the pbxproj we can put it to ignore and everyone should change it to his. Should be possible to write it to pbxproj with the BuildScript.sh which was used to increment the app version, but i disabled it because i don't want that functionality anymore.

**Comment by setegonz** [comment]
Your'e saying that we should work in this section of the pbxproj?

/* Begin PBXProject section */
		4065D2FC1DD3A1AA00B73201 /* Project object */ = {
			isa = PBXProject;
			attributes = {
				LastSwiftUpdateCheck = 0830;
				LastUpgradeCheck = 0820;
				ORGANIZATIONNAME = "Imagin soft";
				TargetAttributes = {
					280D70B51ECFE06A005D2689 = {
						CreatedOnToolsVersion = 8.3.2;
						DevelopmentTeam = 5NHDC5EV44;
						ProvisioningStyle = Automatic;
						SystemCapabilities = {
							com.apple.Push = {
								enabled = 0;
							};
							com.apple.iCloud = {
								enabled = 1;
							};
						};
					};
					4055B1221E0D802300279430 = {
						CreatedOnToolsVersion = 8.2.1;
						DevelopmentTeam = 5NHDC5EV44;
						LastSwiftMigration = 0820;
						ProvisioningStyle = Automatic;
						SystemCapabilities = {
							com.apple.Sandbox = {
								enabled = 1;
							};
						};
					};
					4065D3031DD3A1AA00B73201 = {
						CreatedOnToolsVersion = 8.1;
						DevelopmentTeam = E57U25U2X9;
						LastSwiftMigration = 0820;
						ProvisioningStyle = Automatic;
						SystemCapabilities = {
							com.apple.Push = {
								enabled = 0;
							};
							com.apple.Sandbox = {
								enabled = 1;
							};
							com.apple.iCloud = {
								enabled = 1;
							};
						};
					};
					4065D4011DD4532100B73201 = {
						CreatedOnToolsVersion = 8.1;
						DevelopmentTeam = 5NHDC5EV44;
						ProvisioningStyle = Manual;
						TestTargetID = 4065D3031DD3A1AA00B73201;
					};
					4065D40F1DD4534C00B73201 = {
						CreatedOnToolsVersion = 8.1;
						DevelopmentTeam = 5NHDC5EV44;
						ProvisioningStyle = Automatic;
					};
				};
			};
			buildConfigurationList = 4065D2FF1DD3A1AA00B73201 /* Build configuration list for PBXProject "Jirassic" */;
			compatibilityVersion = "Xcode 3.2";
			developmentRegion = English;
			hasScannedForEncodings = 0;
			knownRegions = (
				en,
				Base,
			);
			mainGroup = 4065D2FB1DD3A1AA00B73201;
			productRefGroup = 4065D3051DD3A1AA00B73201 /* Products */;
			projectDirPath = "";
			projectRoot = "";
			targets = (
				4065D3031DD3A1AA00B73201 /* Jirassic */,
				4065D4011DD4532100B73201 /* JirassicTests */,
				4065D40F1DD4534C00B73201 /* jirassic-cmd */,
				4055B1221E0D802300279430 /* JirassicLauncher */,
				280D70B51ECFE06A005D2689 /* Jirassic Scrum */,
			);
		};
/* End PBXProject section */

**Comment by ralcr** [comment]
Looks more complicated than i thought, is not enough to change the bundle identifier but the signing section too, like you've said. It should be possible with the BuildScript but that will change the pbxproj which must be committed and it will break the project for the other users. I must admit i have no idea how is the right way to do it or if even possible.

**Comment by setegonz** [comment]
Now is getting complicated. I have not idea on how to start working on it, but I have a lot of interest in this project.

**Comment by ralcr** [comment]
No worries, i'll take a look and put the results here, but for the next 1-2 weeks i'll be busy with the first launch in the appstore.

**Comment by ralcr** [comment]
Hi, as of today there's a new target, Jirassic macOS, that can be compiled with some limitations without signing, you can use that. Thanks.
