### ISSUE TITLE
Check for jirassic & jit in ${PATH}

### ISSUE THREAD

**Issue by seanorama** [ralcr/Jirassic#60]
Thanks for the great app.

When checking for the static of jirassic & jit it should check for availability of the command in the ${PATH} not specifically at /usr/local/bin/ as many will want to place the executables in other locations such as ~/bin.

![image](https://user-images.githubusercontent.com/3738610/27576093-d057d44c-5b13-11e7-9f5b-11157497d8c7.png)

**Comment by ralcr** [comment]
Fixed this
