### ISSUE TITLE
Can't Build the app

### ISSUE THREAD

**Issue by danielhq** [ralcr/Jirassic#7]
Hello!
I was looking forward to something like this, as you say JIRA UI sucks.
Unfortunately i don't know anything about swift or desktop programming so i wouldn't know how to fix this, but i can't build.
I git cloned the repo
Imported the project into Xcode
Builded the project
but it gives me 18 errors.
Am i missing something? (btw you should improve the Readme, at least the Compiling part)

Cheers!

**Comment by ralcr** [comment]
Hi, before compiling you need to add a file ParseCredentials and define the Parse credentials and have your own Parse app configured.
I can compile it for you in the next days and let you know, i need to take care of some confusing things, is still work in progress but i use it daily because i know my way around it.

**Comment by danielhq** [comment]
Yes i have done that, created a file External/Parse/ParseCredentials.swift
added the 2 lines:
let parseApplicationId = "<my app id>"
let parseClientId = "<my parse client id>"

**Comment by ralcr** [comment]
Yes please

**Comment by danielhq** [comment]
![screen shot 2016-01-26 at 09 21 59](https://cloud.githubusercontent.com/assets/1651415/12575633/581fac72-c40e-11e5-97c9-2e446912c17e.png)

**Comment by ralcr** [comment]
You're right, the ios app is broken, didn't checked it for a long time. However this is mainly an osx app, you need to chose the Jirassic target from the top left.

**Comment by danielhq** [comment]
You're right it was the iOS version that was broke, in fact when i build it for mac it shows no errors.
But i have no idea where the builded app is located? :D

**Comment by ralcr** [comment]
You can find the location by right clicking jirassic.app in the Products group. Or better just open from Spotlight

**Comment by yqrashawn** [comment]
Same issue and can't find it on app store. Does this become a iOS app? Is there still a mac version?

**Comment by ralcr** [comment]
Hi, it is not yet released on the store, neither mac nor ios. Mac app works, can be compiled, ios is broken at the moment because i'm switching to icloud to sync the data. However there's still a lot of work to do even on the mac app.

**Comment by ralcr** [comment]
Hi, as of today the app is in the store, please check the website http://www.jirassic.com
Compiling the mac app should work without errors now too.
