### ISSUE TITLE
Build input files cannot be found

### ISSUE THREAD

**Issue by Asher1000** [ralcr/Jirassic#86]
error: Build input files cannot be found: '/Users/XXXX/Downloads/Jirassic-master/Vendor/RCPreferences/RCPreferences.swift', '/Users/XXXX/Downloads/Jirassic-master/Vendor/RCLog/src/RCLog.swift', '/Users/XXXX/Downloads/Jirassic-master/Vendor/Keychain/SwiftKeychainWrapper/KeychainWrapper.swift', '/Users/XXXX/Downloads/Jirassic-master/Vendor/RCHttp/src/RCHttp.swift', '/Users/XXXX/Downloads/Jirassic-master/Vendor/Keychain/SwiftKeychainWrapper/KeychainItemAccessibility.swift'

**Comment by ralcr** [comment]
Hi, this are git submodules, they should just work when you do a clone, maybe you can do a new one if you previously had it working because this is a relatively new addition.
