### ISSUE TITLE
Cannot connect to JIRA

### ISSUE THREAD

**Issue by epegzz** [ralcr/Jirassic#89]
![image](https://user-images.githubusercontent.com/770269/47294686-154c2c80-d60e-11e8-8f05-3481fb495d1a.png)

**Comment by epegzz** [comment]
I double checked the login credentials BTW :)

**Comment by ralcr** [comment]
Hi, are you be able to compile the app yourself? I made some improvements in the error message and you could check it in the debugger as well. I found that the login can fail for 3 reasons so far: wrong input details(my user is not an email for example), timeout when the company choses to block access from outside the internal network, and the user needs to solve the captcha.

**Comment by epegzz** [comment]
Hey :) I stopped using it for now. It's still too buggy. It won't save any edits to entries, it behaves weird in many ways, and if you forget at the end of the day to add the last task you were working on then you will not be able to add this afterward. I really like the concept, but right now it has too many usability issues.

This, for example, does not look right :D

<img width="316" alt="image" src="https://user-images.githubusercontent.com/770269/47493409-7f074900-d84f-11e8-9603-9f1c86610726.png">

**Comment by ralcr** [comment]
That's nasty, didn't stressed it like that yet, thank you for reporting and hoping to see you back sometime when is more stable.

**Comment by epegzz** [comment]
I'll be happy to try it again as soon as the following issues are resolved:
- Editing entries (time, title, description) needs to be possible (right now edits do not get saved)
- Adding new entries for past days needs to be possible (right now they are not getting saved)
- I need to be able to see the exact minutes spent on the task (like 3h 21m) for cases where I work on projects that do not use Jira/Tempo

**Comment by ralcr** [comment]
This issues were fixed, thanks for reporting, i'm leaving it open till next release in few weeks.
Let me know if you have more usability issues.

**Comment by ralcr** [comment]
I published a new version, if you try let me know what you think. Thanks
